'''
Author: Yishuo Wang
Date: 2024-08-01 10:13:27
LastEditors: Yishuo Wang
LastEditTime: 2024-08-01 10:15:29
FilePath: /blue_sea_sky_v3/remove_lines_ai.py
Description: remove the lines generated by AI

Copyright (c) 2024 by Yishuo Wang, All Rights Reserved. 
'''
import numpy as np

def remove(data, region):
    data_temp_new = np.copy(data)
    # delete the not relevent edges
    if region == 2:
        data_temp_new[0:2, :] = 0
    elif region == 1:
        rows, cols = data_temp_new.shape
        for p in range(2):
            for q in range(cols):
                if data_temp_new[p, q] == 1:
                    data_temp_new[p, q] = 0
        for p in range(3):
            for q in range(cols):
                if data_temp_new[rows - 1 - p, q] == 1:
                    data_temp_new[rows - 1 - p, q] = 0
    
    return data_temp_new